/**
 * Cline hook adapter for generating executable scripts in .clinerules/hooks/.
 *
 * Cline hooks are executable scripts (no extension) that read JSON from stdin
 * and output JSON to stdout. Context injection uses the `contextModification`
 * field in the response.
 *
 * Only TaskStart is supported (maps from canonical SessionStart).
 * Cline has no SubagentStart or PreCompact equivalents.
 *
 * @see https://docs.cline.bot/features/hooks/hook-reference
 */

import type { CanonicalHook, CanonicalHookEvent, HookAdapter } from '../types';

/**
 * Event name mapping from canonical to Cline.
 * Cline uses PascalCase event names matching their lifecycle.
 */
const CLINE_EVENT_MAP: Record<CanonicalHookEvent, string | undefined> = {
	SessionStart: 'TaskStart',
	SubagentStart: undefined, // Cline has no subagent concept
	PreCompact: undefined, // Cline has no compaction concept
	PreToolUse: 'PreToolUse',
	PostToolUse: 'PostToolUse',
	SessionEnd: 'TaskComplete',
};

/**
 * Cline MCP tool name for Constellation.
 * Cline uses just the tool name without server prefix.
 */
const CLINE_MCP_TOOL_NAME = 'query_code_graph';

/**
 * Get the script filename for a hook event.
 * Cline hook scripts have no file extension.
 */
function getScriptName(event: CanonicalHookEvent): string | undefined {
	const clineEvent = CLINE_EVENT_MAP[event];
	return clineEvent; // Script name IS the event name (no extension)
}

/**
 * Adapter for generating Cline hook scripts.
 *
 * Cline hooks are:
 * - Executable scripts in .clinerules/hooks/ (project) or ~/Documents/Cline/Hooks/ (global)
 * - Named exactly after the hook type (e.g., TaskStart, PreToolUse)
 * - No file extension
 * - Read JSON from stdin, output JSON to stdout
 *
 * Output protocol:
 * ```json
 * {
 *   "cancel": false,
 *   "contextModification": "Injected context here"
 * }
 * ```
 */
export class ClineHookAdapter implements HookAdapter {
	readonly id = 'cline';
	readonly displayName = 'Cline';

	mapEventName(event: CanonicalHookEvent): string | undefined {
		return CLINE_EVENT_MAP[event];
	}

	generateConfig(_hooks: CanonicalHook[]): Record<string, unknown> {
		// Cline doesn't use a config file for hooks - just scripts
		// Return empty object (HooksWriter will skip writing if empty)
		return {};
	}

	customizePrompt(hook: CanonicalHook): string {
		return hook.content.replace(/\{MCP_TOOL_NAME\}/g, CLINE_MCP_TOOL_NAME);
	}

	generateAuxiliaryFiles(
		hooks: CanonicalHook[],
	): Map<string, string> | undefined {
		const files = new Map<string, string>();

		for (const hook of hooks) {
			const scriptName = getScriptName(hook.event);
			if (!scriptName) continue; // Skip unsupported events

			const scriptPath = `.clinerules/hooks/${scriptName}`;
			const scriptContent = this.generateScript(hook);

			files.set(scriptPath, scriptContent);
		}

		return files.size > 0 ? files : undefined;
	}

	private generateScript(hook: CanonicalHook): string {
		const customizedPrompt = this.customizePrompt(hook);
		// Escape for JSON: backslashes, quotes, and convert newlines to \n
		// SECURITY NOTE: Using single-quoted heredoc delimiter ('CONSTELLATION_EOF')
		// prevents shell variable expansion in the output. Do not change to unquoted.
		const escapedPrompt = customizedPrompt
			.replace(/\\/g, '\\\\')
			.replace(/"/g, '\\"')
			.replace(/\n/g, '\\n');

		return `#!/bin/bash
# Constellation ${hook.event} Hook for Cline
# Generated by constellation-cli - DO NOT EDIT
#
# This script injects Constellation guidance at task start.
# It reads JSON input from stdin (ignored) and outputs JSON with contextModification.

cat << 'CONSTELLATION_EOF'
{
  "cancel": false,
  "contextModification": "${escapedPrompt}"
}
CONSTELLATION_EOF
`;
	}
}
