import { describe, expect, it } from '@jest/globals';
import { ClineHookAdapter } from '../../../../src/hooks/adapters/cline.adapter';
import type { CanonicalHook } from '../../../../src/hooks/types';

describe('ClineHookAdapter', () => {
	const adapter = new ClineHookAdapter();

	describe('properties', () => {
		it('should have correct id', () => {
			expect(adapter.id).toBe('cline');
		});

		it('should have correct displayName', () => {
			expect(adapter.displayName).toBe('Cline');
		});
	});

	describe('mapEventName', () => {
		it('should map SessionStart to TaskStart', () => {
			expect(adapter.mapEventName('SessionStart')).toBe('TaskStart');
		});

		it('should return undefined for SubagentStart (not supported)', () => {
			expect(adapter.mapEventName('SubagentStart')).toBeUndefined();
		});

		it('should return undefined for PreCompact (not supported)', () => {
			expect(adapter.mapEventName('PreCompact')).toBeUndefined();
		});

		it('should map PreToolUse to PreToolUse', () => {
			expect(adapter.mapEventName('PreToolUse')).toBe('PreToolUse');
		});

		it('should map PostToolUse to PostToolUse', () => {
			expect(adapter.mapEventName('PostToolUse')).toBe('PostToolUse');
		});

		it('should map SessionEnd to TaskComplete', () => {
			expect(adapter.mapEventName('SessionEnd')).toBe('TaskComplete');
		});
	});

	describe('customizePrompt', () => {
		it('should replace {MCP_TOOL_NAME} placeholder with Cline tool name', () => {
			const hook: CanonicalHook = {
				event: 'SessionStart',
				type: 'prompt',
				content: 'Use {MCP_TOOL_NAME} for code analysis.',
			};

			const result = adapter.customizePrompt(hook);

			expect(result).toBe('Use code_intel for code analysis.');
		});

		it('should replace multiple {MCP_TOOL_NAME} occurrences', () => {
			const hook: CanonicalHook = {
				event: 'SessionStart',
				type: 'prompt',
				content:
					'{MCP_TOOL_NAME} is primary. Always use {MCP_TOOL_NAME} first.',
			};

			const result = adapter.customizePrompt(hook);

			expect(result).toBe(
				'code_intel is primary. Always use code_intel first.',
			);
		});

		it('should return content unchanged if no placeholder present', () => {
			const hook: CanonicalHook = {
				event: 'SessionStart',
				type: 'prompt',
				content: 'No placeholder here.',
			};

			const result = adapter.customizePrompt(hook);

			expect(result).toBe('No placeholder here.');
		});
	});

	describe('generateConfig', () => {
		it('should return empty object (Cline uses scripts, not config)', () => {
			const hooks: CanonicalHook[] = [
				{
					event: 'SessionStart',
					type: 'prompt',
					content: 'Test prompt',
				},
			];

			const config = adapter.generateConfig(hooks);

			expect(config).toEqual({});
		});
	});

	describe('generateAuxiliaryFiles', () => {
		it('should generate script for SessionStart as TaskStart', () => {
			const hooks: CanonicalHook[] = [
				{
					event: 'SessionStart',
					type: 'prompt',
					content: 'Use {MCP_TOOL_NAME} as primary tool.',
				},
			];

			const files = adapter.generateAuxiliaryFiles(hooks);

			expect(files).toBeDefined();
			expect(files!.size).toBe(1);
			expect(files!.has('.clinerules/hooks/TaskStart')).toBe(true);
		});

		it('should generate script with proper shebang and header', () => {
			const hooks: CanonicalHook[] = [
				{
					event: 'SessionStart',
					type: 'prompt',
					content: 'Test content',
				},
			];

			const files = adapter.generateAuxiliaryFiles(hooks);
			const script = files!.get('.clinerules/hooks/TaskStart');

			expect(script).toContain('#!/bin/bash');
			expect(script).toContain('Constellation SessionStart Hook for Cline');
			expect(script).toContain('Generated by constellation-cli');
		});

		it('should use contextModification for context injection', () => {
			const hooks: CanonicalHook[] = [
				{
					event: 'SessionStart',
					type: 'prompt',
					content: 'Test content',
				},
			];

			const files = adapter.generateAuxiliaryFiles(hooks);
			const script = files!.get('.clinerules/hooks/TaskStart');

			expect(script).toContain('"cancel": false');
			expect(script).toContain('"contextModification"');
		});

		it('should replace {MCP_TOOL_NAME} in script content', () => {
			const hooks: CanonicalHook[] = [
				{
					event: 'SessionStart',
					type: 'prompt',
					content: 'Use {MCP_TOOL_NAME} for analysis.',
				},
			];

			const files = adapter.generateAuxiliaryFiles(hooks);
			const script = files!.get('.clinerules/hooks/TaskStart');

			expect(script).toContain('code_intel');
			expect(script).not.toContain('{MCP_TOOL_NAME}');
		});

		it('should skip unsupported events (SubagentStart, PreCompact)', () => {
			const hooks: CanonicalHook[] = [
				{
					event: 'SubagentStart',
					type: 'prompt',
					content: 'Subagent prompt',
				},
				{
					event: 'PreCompact',
					type: 'prompt',
					content: 'Preserve context',
				},
			];

			const files = adapter.generateAuxiliaryFiles(hooks);

			expect(files).toBeUndefined();
		});

		it('should return undefined for empty hooks array', () => {
			const files = adapter.generateAuxiliaryFiles([]);

			expect(files).toBeUndefined();
		});

		it('should escape special characters in prompt content', () => {
			const hooks: CanonicalHook[] = [
				{
					event: 'SessionStart',
					type: 'prompt',
					content: 'Line 1\nLine 2\n"quoted"',
				},
			];

			const files = adapter.generateAuxiliaryFiles(hooks);
			const script = files!.get('.clinerules/hooks/TaskStart');

			// Should have escaped newlines and quotes for JSON
			expect(script).toContain('\\n');
			expect(script).toContain('\\"quoted\\"');
		});

		it('should only generate TaskStart from Constellation hooks', () => {
			// Simulate the actual Constellation hooks (SessionStart, SubagentStart, PreCompact)
			const hooks: CanonicalHook[] = [
				{
					event: 'SessionStart',
					type: 'prompt',
					content: 'Session start prompt',
					matcher: '.*',
				},
				{
					event: 'SubagentStart',
					type: 'prompt',
					content: 'Subagent prompt',
					matcher: 'Explore|Plan',
				},
				{
					event: 'PreCompact',
					type: 'prompt',
					content: 'Preserve context',
					matcher: '.*',
				},
			];

			const files = adapter.generateAuxiliaryFiles(hooks);

			// Only SessionStart should produce a file (as TaskStart)
			expect(files).toBeDefined();
			expect(files!.size).toBe(1);
			expect(files!.has('.clinerules/hooks/TaskStart')).toBe(true);
		});
	});
});
